version: '3'

services:

  strava-oauth:
    container_name: strava-oauth
    restart: always
    build: .
    env_file:
      - .env
    # environment: 
    #   - APP_URL=http://test.velometria.com
    ports:
      - "5042:5042"
    expose:
      - "5042"
    command: python api.py